### PR TITLE
super-nova-ficura

### PR DESCRIPTION
**Pull request by PolygonUnicorn**
Hej ud2lal jsem super novou dokumentaci

### CODE REVIEW

**Comment by elisthedoc** [comment]
> Hej ud2lal jsem super novou dokumen

are you sure about that

**Comment by PolygonUnicorn** [comment]
._.

**Comment by PolygonUnicorn** [comment]
I'm not

**Comment by FeedTheMEe** [comment]
Maple sirup

**Comment by elisthedoc** [comment]
> 
> 
> Maple sirup

u want, i can take some from job

**Pull request merged**
